/**
 * Full scraper catalog for the library page.
 * Scrapers with a `slug` have a detail page at /templates/[slug].
 * Others link directly to the Bright Data console.
 */

export type CatalogScraper = {
  id: string;
  name: string;
  domain: string;
  desc: string;
  category: string;
  icon: string;
  color: string;
  fields: string[];
  views: string;
  downloads: string;
  slug?: string;
  popular?: boolean;
};

export const CATALOG_CATEGORIES = [
  "All",
  "Social Media",
  "E-commerce",
  "Business (B2B)",
  "Jobs",
  "Real Estate",
  "Travel",
  "Search",
  "News & Media",
  "Finance",
] as const;

const DOMAIN_CATEGORY_MAP: Record<string, string> = {
  "linkedin.com": "Business (B2B)",
  "crunchbase.com": "Business (B2B)",
  "glassdoor.com": "Business (B2B)",
  "apollo.io": "Business (B2B)",
  "zoominfo.com": "Business (B2B)",
  "pitchbook.com": "Business (B2B)",
  "dnb.com": "Business (B2B)",
  "g2.com": "Business (B2B)",
  "capterra.com": "Business (B2B)",
  "trustpilot.com": "Business (B2B)",
  "yelp.com": "Business (B2B)",
  "amazon.com": "E-commerce",
  "walmart.com": "E-commerce",
  "ebay.com": "E-commerce",
  "etsy.com": "E-commerce",
  "shopify.com": "E-commerce",
  "target.com": "E-commerce",
  "bestbuy.com": "E-commerce",
  "alibaba.com": "E-commerce",
  "aliexpress.com": "E-commerce",
  "tiktok.com": "Social Media",
  "instagram.com": "Social Media",
  "facebook.com": "Social Media",
  "x.com": "Social Media",
  "twitter.com": "Social Media",
  "youtube.com": "Social Media",
  "reddit.com": "Social Media",
  "pinterest.com": "Social Media",
  "threads.net": "Social Media",
  "telegram.org": "Social Media",
  "discord.com": "Social Media",
  "snapchat.com": "Social Media",
  "indeed.com": "Jobs",
  "glassdoor.com/job": "Jobs",
  "ziprecruiter.com": "Jobs",
  "monster.com": "Jobs",
  "dice.com": "Jobs",
  "upwork.com": "Jobs",
  "fiverr.com": "Jobs",
  "zillow.com": "Real Estate",
  "realtor.com": "Real Estate",
  "redfin.com": "Real Estate",
  "trulia.com": "Real Estate",
  "rightmove.co.uk": "Real Estate",
  "airbnb.com": "Travel",
  "booking.com": "Travel",
  "tripadvisor.com": "Travel",
  "expedia.com": "Travel",
  "hotels.com": "Travel",
  "google.com/maps": "Search",
  "google.com": "Search",
  "bing.com": "Search",
  "finance.yahoo.com": "Finance",
  "bloomberg.com": "Finance",
  "reuters.com": "News & Media",
  "news.ycombinator.com": "News & Media",
  "techcrunch.com": "News & Media",
  "bbc.com": "News & Media",
  "cnn.com": "News & Media",
};

/**
 * Auto-assign a category based on domain. Falls back to "Search" for unknown domains.
 * Use this when adding new scrapers to avoid manual category guessing.
 */
export function assignCategory(domain: string): string {
  const d = domain.toLowerCase().replace(/^www\./, "");
  for (const [pattern, category] of Object.entries(DOMAIN_CATEGORY_MAP)) {
    if (d === pattern || d.endsWith("." + pattern) || d.startsWith(pattern)) {
      return category;
    }
  }
  return "Search";
}

export const catalog: CatalogScraper[] = [
  {
    id: "linkedin-people",
    name: "LinkedIn People Profiles",
    domain: "linkedin.com",
    desc: "Professional data: name, headline, company, experience, skills, and certifications",
    category: "Business (B2B)",
    icon: "in",
    color: "#0A66C2",
    fields: ["ID", "Name", "City", "Country code", "Position", "About", "Posts", "Current company", "Industry", "Connections", "Education", "Skills", "Certifications", "Languages", "Profile image", "Headline", "Experience years", "Email", "Phone", "Websites", "Recommendations count", "Volunteer experience", "Publications", "Courses", "Honors & awards", "Open to work"],
    views: "118.3K+",
    downloads: "11.1K+",
    slug: "linkedin-profile",
    popular: true,
  },
  {
    id: "amazon-products",
    name: "Amazon Products",
    domain: "amazon.com",
    desc: "Extract prices, reviews, stock levels & seller data from any Amazon product",
    category: "E-commerce",
    icon: "A",
    color: "#FF9900",
    fields: ["Title", "Seller name", "Brand", "Description", "Initial price", "Final price", "Currency", "Availability", "Reviews count", "Rating", "ASIN", "Categories", "Images", "Delivery", "Variations", "Bestseller rank", "Dimensions", "Weight", "Features", "Coupon", "Subscribe & Save", "Frequently bought together", "Color options", "Size options", "Country of origin", "Date first available"],
    views: "34.7K+",
    downloads: "5.7K+",
    slug: "amazon-product",
    popular: true,
  },
  {
    id: "linkedin-companies",
    name: "LinkedIn Company Info",
    domain: "linkedin.com",
    desc: "Company details: industry, size, funding, specialties, and employee count",
    category: "Business (B2B)",
    icon: "in",
    color: "#0A66C2",
    fields: ["ID", "Name", "Country code", "Locations", "Followers", "Employees in LinkedIn", "About", "Specialties", "Industry", "Website", "Founded", "Company size", "Headquarters", "Type", "Logo", "Cover image", "Affiliated companies", "Recent updates", "Job openings count", "Funding info", "Growth rate", "Employee distribution"],
    views: "33K+",
    downloads: "3.5K+",
  },
  {
    id: "instagram-profiles",
    name: "Instagram Profiles",
    domain: "instagram.com",
    desc: "Followers, posts, bio, engagement rate, recent media, and growth metrics",
    category: "Social Media",
    icon: "◎",
    color: "#E4405F",
    fields: ["Account", "Fbid", "ID", "Followers", "Following", "Posts count", "Is business account", "Is professional account", "Is verified", "Biography", "External URL", "Category", "Profile pic", "Full name", "Engagement rate", "Recent posts", "Story highlights count", "Reels count", "Contact phone", "Contact email", "Business address", "Avg likes per post", "Avg comments per post", "Growth rate 30d"],
    views: "21.9K+",
    downloads: "3.4K+",
    slug: "instagram-profile",
    popular: true,
  },
  {
    id: "crunchbase-companies",
    name: "Crunchbase Companies",
    domain: "crunchbase.com",
    desc: "Startup data: funding rounds, investors, revenue range, and key people",
    category: "Business (B2B)",
    icon: "Cb",
    color: "#0288D1",
    fields: ["Name", "URL", "ID", "Cb rank", "Region", "About", "Industries", "Operating status", "Founded date", "Funding total", "Last funding type", "Employees", "Revenue range", "Website", "Headquarters", "Investors count", "IPO status", "Last funding date", "Acquisitions", "Sub-organizations", "Board members", "Key people", "Technology stack", "Similar companies"],
    views: "15.4K+",
    downloads: "1.6K+",
  },
  {
    id: "linkedin-jobs",
    name: "LinkedIn Job Listings",
    domain: "linkedin.com",
    desc: "Job title, salary, skills required, company info, and applicant count",
    category: "Jobs",
    icon: "in",
    color: "#0A66C2",
    fields: ["URL", "Job posting id", "Job title", "Company name", "Company id", "Job location", "Job summary", "Job seniority level", "Employment type", "Job function", "Industries", "Applicants count", "Posted date", "Salary range", "Remote allowed", "Skills required", "Benefits", "Company size", "Company followers", "Job description full", "Apply URL", "Referral bonus", "Hiring manager", "Easy apply"],
    views: "15.1K+",
    downloads: "2.2K+",
    popular: true,
  },
  {
    id: "instagram-posts",
    name: "Instagram Posts",
    domain: "instagram.com",
    desc: "Post content, likes, comments, hashtags, engagement rate, and media URLs",
    category: "Social Media",
    icon: "◎",
    color: "#E4405F",
    fields: ["URL", "User posted", "Description", "Hashtags", "Num comments", "Date posted", "Likes", "Photos", "Video URL", "Location", "Tagged users", "Is sponsored", "Engagement rate", "Caption", "Alt text", "Carousel items", "Saves count", "Shares count", "Audio title", "Audio artist", "Filter used", "Aspect ratio", "Is pinned"],
    views: "13K+",
    downloads: "1.6K+",
  },
  {
    id: "google-maps",
    name: "Google Maps Businesses",
    domain: "google.com/maps",
    desc: "Business name, address, phone, ratings, reviews, hours, and photos",
    category: "Search",
    icon: "G",
    color: "#4285F4",
    fields: ["Place id", "URL", "Country", "Name", "Category", "Address", "Description", "Business details", "Phone", "Website", "Rating", "Reviews count", "Opening hours", "Photos", "Latitude", "Longitude", "Price level", "Popular times", "Service options", "Accessibility", "Atmosphere", "Parking", "Payment methods", "Reservation link", "Menu link", "Owner response rate"],
    views: "12.8K+",
    downloads: "1.6K+",
    slug: "google-maps",
    popular: true,
  },
  {
    id: "zillow-listings",
    name: "Zillow Properties",
    domain: "zillow.com",
    desc: "Property price, beds, baths, Zestimate, lot size, and neighborhood scores",
    category: "Real Estate",
    icon: "Z",
    color: "#006AFF",
    fields: ["Zpid", "City", "State", "HomeStatus", "Address", "Bedrooms", "Bathrooms", "Living area", "Lot size", "Price", "Zestimate", "Year built", "Property type", "HOA fee", "Tax assessment", "Price history", "Nearby schools", "Walk score", "Transit score", "Bike score", "Days on Zillow", "Views count", "Saves count", "Agent name", "Agent phone", "Heating", "Cooling", "Flooring"],
    views: "11.9K+",
    downloads: "1.2K+",
    slug: "zillow-listings",
  },
  {
    id: "linkedin-posts",
    name: "LinkedIn Posts",
    domain: "linkedin.com",
    desc: "Post text, reactions, comments, shares, impressions, and engagement data",
    category: "Social Media",
    icon: "in",
    color: "#0A66C2",
    fields: ["URL", "ID", "User id", "User url", "Title", "Headline", "Post text", "Date posted", "Likes", "Comments", "Shares", "Reactions breakdown", "Media type", "Article URL", "Hashtags", "Mentioned users", "Impressions", "Click-through rate", "Is repost", "Original author", "Follower count at post", "Content type"],
    views: "11.2K+",
    downloads: "1.4K+",
  },
  {
    id: "x-posts",
    name: "X (Twitter) Posts",
    domain: "x.com",
    desc: "Tweet text, likes, retweets, replies, views, and engagement metrics",
    category: "Social Media",
    icon: "𝕏",
    color: "#14171A",
    fields: ["ID", "User posted", "Name", "Description", "Date posted", "Photos", "URL", "Quoted post", "Likes", "Retweets", "Replies", "Bookmarks", "Views", "Is verified", "Language", "Hashtags", "Mentioned users", "Card type", "Poll data", "Thread position", "Source app", "Sensitive content", "Community note", "Engagement rate"],
    views: "10.2K+",
    downloads: "1.2K+",
  },
  {
    id: "tiktok-profiles",
    name: "TikTok Profiles",
    domain: "tiktok.com",
    desc: "Followers, engagement rate, video count, bio, and growth metrics",
    category: "Social Media",
    icon: "♪",
    color: "#00F2EA",
    fields: ["Account id", "Nickname", "Biography", "Avg engagement rate", "Comment engagement rate", "Like engagement rate", "Bio link", "Predicted lang", "Followers", "Following", "Likes", "Videos count", "Verified", "Profile pic", "Region", "Account created", "Avg views per video", "Top hashtags", "Branded content", "Business account", "Category", "Growth rate 30d"],
    views: "8.2K+",
    downloads: "953+",
    slug: "tiktok-posts",
  },
  {
    id: "youtube-videos",
    name: "YouTube Videos",
    domain: "youtube.com",
    desc: "Title, views, likes, comments, duration, tags, and channel data",
    category: "Social Media",
    icon: "▶",
    color: "#FF0000",
    fields: ["URL", "Title", "Youtuber", "Video url", "Video length", "Likes", "Views", "Comments count", "Description", "Published date", "Thumbnail", "Tags", "Category", "Captions available", "Channel subscribers", "Is live", "Resolution", "Chapters", "End screen links", "Sponsor segments", "Language", "Age restricted", "Premiere date", "Membership only"],
    views: "7.9K+",
    downloads: "708+",
  },
  {
    id: "amazon-reviews",
    name: "Amazon Reviews",
    domain: "amazon.com",
    desc: "Review text, rating, verified purchase status, helpful votes, and author info",
    category: "E-commerce",
    icon: "A",
    color: "#FF9900",
    fields: ["URL", "Product name", "Product rating", "Rating", "Author name", "ASIN", "Review title", "Review text", "Date", "Verified purchase", "Helpful votes", "Images", "Country", "Variant", "Star breakdown", "Review length", "Reviewer rank", "Reviewer badge", "Video review", "Response from seller", "Edition", "Size purchased", "Color purchased"],
    views: "7.2K+",
    downloads: "852+",
    slug: "amazon-reviews",
  },
  {
    id: "tiktok-posts",
    name: "TikTok Posts",
    domain: "tiktok.com",
    desc: "Video metrics: plays, shares, comments, hashtags, and music details",
    category: "Social Media",
    icon: "♪",
    color: "#00F2EA",
    fields: ["URL", "Post id", "Description", "Create time", "Digg count", "Share count", "Collect count", "Comment count", "Play count", "Music title", "Music author", "Hashtags", "Duration", "Is ad", "Author nickname", "Effects", "Stitch enabled", "Duet enabled", "Original sound", "Cover image", "Video quality", "Location tag", "Challenges"],
    views: "6.6K+",
    downloads: "866+",
  },
  {
    id: "facebook-posts",
    name: "Facebook Page Posts",
    domain: "facebook.com",
    desc: "Post content, reactions, comments, shares, media, and audience insights",
    category: "Social Media",
    icon: "f",
    color: "#1877F2",
    fields: ["URL", "Post id", "User url", "Username", "Content", "Date posted", "Hashtags", "Num comments", "Reactions", "Shares", "Photos", "Video URL", "Is sponsored", "Post type", "Link preview", "Reaction breakdown", "Top comments", "Tagged pages", "Check-in location", "Event link", "Audience", "Edited"],
    views: "6.5K+",
    downloads: "623+",
  },
  {
    id: "indeed-jobs",
    name: "Indeed Job Listings",
    domain: "indeed.com",
    desc: "Job title, salary, benefits, qualifications, company rating, and location",
    category: "Jobs",
    icon: "i",
    color: "#2164F3",
    fields: ["Jobid", "Company name", "Date posted", "Job title", "Description text", "Benefits", "Qualifications", "Job type", "Salary", "Location", "Remote", "Experience level", "Education required", "Skills", "Company rating", "Urgently hiring", "Apply link", "Responsive employer", "Hiring multiple", "Schedule", "Supplemental pay", "Work setting", "Industry"],
    views: "6.4K+",
    downloads: "759+",
  },
  {
    id: "walmart-products",
    name: "Walmart Products",
    domain: "walmart.com",
    desc: "Price, brand, rating, availability, shipping options, and specifications",
    category: "E-commerce",
    icon: "W",
    color: "#0071DC",
    fields: ["URL", "Final price", "SKU", "Currency", "GTIN", "Specifications", "Image urls", "Top reviews", "Brand", "Model", "Category", "Availability", "Seller", "Rating", "Reviews count", "Shipping", "Return policy", "Walmart+ eligible", "Rollback price", "Pickup available", "Same-day delivery", "Warranty", "Condition", "Quantity available"],
    views: "5.5K+",
    downloads: "857+",
  },
  {
    id: "tiktok-shop",
    name: "TikTok Shop Products",
    domain: "tiktok.com",
    desc: "Product price, ratings, sold count, shop info, and variant details",
    category: "E-commerce",
    icon: "♪",
    color: "#00F2EA",
    fields: ["URL", "Title", "Available", "Description", "Currency", "Initial price", "Final price", "Discount percent", "Rating", "Reviews count", "Sold count", "Shop name", "Images", "Variants", "Category", "Shipping info", "Return policy", "Shop rating", "Shop followers", "Video reviews", "Size guide", "Material", "Bundle deals"],
    views: "5.3K+",
    downloads: "661+",
  },
  {
    id: "youtube-channels",
    name: "YouTube Channels",
    domain: "youtube.com",
    desc: "Subscribers, total views, upload frequency, country, and channel stats",
    category: "Social Media",
    icon: "▶",
    color: "#FF0000",
    fields: ["URL", "Handle", "Banner img", "Profile image", "Name", "Subscribers", "Description", "Country", "Joined date", "Total views", "Videos count", "Links", "Is verified", "Category", "Average views", "Upload frequency", "Shorts count", "Live streams count", "Community posts", "Memberships available", "Merchandise links", "Playlists count"],
    views: "4.4K+",
    downloads: "502+",
  },
  {
    id: "reddit-posts",
    name: "Reddit Posts",
    domain: "reddit.com",
    desc: "Title, upvotes, comments, awards, community info, and post content",
    category: "Social Media",
    icon: "R",
    color: "#FF4500",
    fields: ["Post id", "URL", "User posted", "Title", "Description", "Num comments", "Date posted", "Community name", "Upvotes", "Downvotes", "Awards", "Is NSFW", "Flair", "Media", "Crosspost", "Top comments", "Upvote ratio", "Is pinned", "Is locked", "Community members", "Author karma", "Post type", "External link"],
    views: "4.4K+",
    downloads: "421+",
  },
  {
    id: "glassdoor-companies",
    name: "Glassdoor Companies",
    domain: "glassdoor.com",
    desc: "Company ratings, CEO approval, salary ranges, benefits, and culture scores",
    category: "Business (B2B)",
    icon: "G",
    color: "#0CAA41",
    fields: ["ID", "Company", "Ratings overall", "Details size", "Details founded", "Details type", "Country code", "Company type", "Revenue", "Industry", "CEO name", "CEO approval", "Recommend to friend", "Culture rating", "Work-life balance", "Benefits rating", "Career opportunities", "Senior management", "Diversity score", "Interview difficulty", "Salary ranges", "Top benefits listed"],
    views: "4.2K+",
    downloads: "378+",
  },
  {
    id: "google-maps-reviews",
    name: "Google Maps Reviews",
    domain: "google.com/maps",
    desc: "Review text, rating, reviewer info, photos, and business response",
    category: "Search",
    icon: "G",
    color: "#4285F4",
    fields: ["URL", "Place id", "Place name", "Country", "Address", "Review id", "Reviewer name", "Reviews by reviewer", "Rating", "Review text", "Date", "Response text", "Photos", "Language", "Is local guide", "Reviewer level", "Visit type", "Meal type", "Price paid", "Service rating", "Food rating", "Atmosphere rating"],
    views: "4.1K+",
    downloads: "299+",
    slug: "google-maps-reviews",
  },
  {
    id: "instagram-reels",
    name: "Instagram Reels",
    domain: "instagram.com",
    desc: "Views, likes, shares, saves, duration, music, and engagement data",
    category: "Social Media",
    icon: "◎",
    color: "#E4405F",
    fields: ["URL", "User posted", "Description", "Hashtags", "Num comments", "Date posted", "Likes", "Views", "Duration", "Music title", "Music artist", "Thumbnail", "Is sponsored", "Location", "Tagged users", "Shares count", "Saves count", "Plays count", "Audio original", "Effect name", "Collab account", "Is remix", "Caption"],
    views: "3.6K+",
    downloads: "435+",
  },
  {
    id: "airbnb-properties",
    name: "Airbnb Properties",
    domain: "airbnb.com",
    desc: "Listing price, location, amenities, reviews, host info, and availability",
    category: "Travel",
    icon: "⌂",
    color: "#FF5A5F",
    fields: ["Name", "Price", "Image", "Description", "Category", "Availability", "Discount", "Reviews", "Rating", "Host name", "Superhost", "Location", "Amenities", "Bedrooms", "Bathrooms", "Max guests", "Check-in", "House rules", "Cancellation policy", "Cleaning fee", "Service fee", "Response rate", "Response time", "Languages spoken", "Neighborhood", "Safety features"],
    views: "3.6K+",
    downloads: "575+",
  },
  {
    id: "x-profiles",
    name: "X (Twitter) Profiles",
    domain: "x.com",
    desc: "Bio, followers, following, tweet count, verification status, and engagement",
    category: "Social Media",
    icon: "𝕏",
    color: "#14171A",
    fields: ["X id", "URL", "ID", "Profile name", "Biography", "Is verified", "Profile image link", "External link", "Followers", "Following", "Tweets count", "Joined date", "Location", "Banner image", "Pinned tweet", "Subscription type", "Verified type", "Professional category", "Lists count", "Spaces hosted", "Average engagement", "Tweet frequency"],
    views: "3.4K+",
    downloads: "220+",
  },
  {
    id: "glassdoor-reviews",
    name: "Glassdoor Reviews",
    domain: "glassdoor.com",
    desc: "Employee reviews: pros, cons, ratings, job title, and management feedback",
    category: "Business (B2B)",
    icon: "G",
    color: "#0CAA41",
    fields: ["Overview id", "Review id", "Review url", "Rating date", "Count helpful", "Employee job title", "Employee length", "Pros", "Cons", "Advice to management", "Overall rating", "Work-life rating", "Culture rating", "Career rating", "Compensation rating", "Senior mgmt rating", "Current employee", "Employment status", "Location", "Recommend", "Business outlook", "CEO opinion"],
    views: "3.3K+",
    downloads: "544+",
  },
  {
    id: "booking-hotels",
    name: "Booking.com Hotels",
    domain: "booking.com",
    desc: "Room prices, ratings, amenities, location, photos, and cancellation policy",
    category: "Travel",
    icon: "B",
    color: "#003580",
    fields: ["URL", "Hotel id", "Title", "Location", "Country", "City", "Metro access", "Images", "Price", "Rating", "Reviews count", "Stars", "Amenities", "Room types", "Free cancellation", "Breakfast included", "Distance to center", "Check-in time", "Check-out time", "Sustainability level", "Genius discount", "Staff rating", "Cleanliness rating", "WiFi rating", "Value rating"],
    views: "3.2K+",
    downloads: "378+",
  },
  {
    id: "yahoo-finance",
    name: "Yahoo Finance",
    domain: "finance.yahoo.com",
    desc: "Stock price, market cap, P/E ratio, earnings, dividends, and analyst ratings",
    category: "Finance",
    icon: "Y",
    color: "#6001D2",
    fields: ["Name", "Company id", "Entity type", "Summary", "Stock ticker", "Currency", "Earnings date", "Exchange", "Market cap", "PE ratio", "52-week high", "52-week low", "Dividend yield", "Revenue", "Profit margin", "Employees", "EPS", "Beta", "Average volume", "Open price", "Previous close", "Day range", "Target price", "Analyst rating"],
    views: "3K+",
    downloads: "351+",
  },
  {
    id: "instagram-comments",
    name: "Instagram Comments",
    domain: "instagram.com",
    desc: "Comment text, likes, replies, author info, and sentiment data",
    category: "Social Media",
    icon: "◎",
    color: "#E4405F",
    fields: ["URL", "Comment user", "Comment user url", "Comment date", "Comment text", "Likes number", "Replies number", "Replies", "Is verified", "User followers", "User profile pic", "Post URL", "Mentioned users", "Hashtags in comment", "Is pinned", "Is creator reply", "Comment language", "Sentiment", "User engagement rate"],
    views: "2.8K+",
    downloads: "320+",
  },
  {
    id: "google-search",
    name: "Google Search Results",
    domain: "google.com",
    desc: "SERP results: titles, URLs, snippets, ads, and rich features",
    category: "Search",
    icon: "G",
    color: "#4285F4",
    fields: ["Query", "Position", "Title", "URL", "Description", "Displayed URL", "Sitelinks", "Knowledge panel", "People also ask", "Related searches", "Featured snippet", "Ads", "Shopping results", "Images", "Videos", "News", "Local pack", "Language", "Country", "Device type", "Total results"],
    views: "9.8K+",
    downloads: "1.1K+",
  },
  {
    id: "ebay-products",
    name: "eBay Products",
    domain: "ebay.com",
    desc: "Price, bids, condition, seller rating, shipping cost, and item specifics",
    category: "E-commerce",
    icon: "e",
    color: "#E53238",
    fields: ["Item ID", "Title", "Price", "Currency", "Condition", "Seller", "Seller rating", "Bids", "Time left", "Shipping cost", "Location", "Returns", "Category", "Brand", "Images", "Watchers", "Sold count", "Item specifics", "Description"],
    views: "4.8K+",
    downloads: "520+",
  },
  {
    id: "etsy-products",
    name: "Etsy Products",
    domain: "etsy.com",
    desc: "Handmade item details: price, shop rating, materials, tags, and reviews",
    category: "E-commerce",
    icon: "E",
    color: "#F56400",
    fields: ["Listing ID", "Title", "Price", "Currency", "Shop name", "Shop rating", "Sales count", "Description", "Tags", "Materials", "Category", "Images", "Reviews count", "Favorites", "Shipping", "Customizable", "Digital download", "Processing time"],
    views: "3.2K+",
    downloads: "310+",
  },
  {
    id: "shopify-products",
    name: "Shopify Store Products",
    domain: "shopify.com",
    desc: "Product catalog: price, variants, inventory, images, and vendor info",
    category: "E-commerce",
    icon: "S",
    color: "#96BF48",
    fields: ["Product ID", "Title", "Handle", "Price", "Compare at price", "Vendor", "Type", "Tags", "Description", "Images", "Variants", "SKU", "Inventory", "Weight", "Published date", "Collection", "Options", "Barcode"],
    views: "2.9K+",
    downloads: "275+",
  },
  {
    id: "tripadvisor-hotels",
    name: "Tripadvisor Hotels",
    domain: "tripadvisor.com",
    desc: "Hotel ratings, price range, amenities, rankings, and traveler reviews",
    category: "Travel",
    icon: "T",
    color: "#00AF87",
    fields: ["Hotel ID", "Name", "Rating", "Reviews count", "Price range", "Location", "Address", "Amenities", "Room types", "Photos", "Ranking", "Awards", "Nearby attractions", "Restaurant count", "Class", "Check-in", "Languages spoken", "Property type"],
    views: "2.7K+",
    downloads: "288+",
  },
  {
    id: "pinterest-pins",
    name: "Pinterest Pins",
    domain: "pinterest.com",
    desc: "Pin images, descriptions, saves, board info, and related content",
    category: "Social Media",
    icon: "P",
    color: "#E60023",
    fields: ["Pin ID", "Title", "Description", "Image URL", "Link", "Board name", "Pinner name", "Saves count", "Comments count", "Domain", "Created at", "Tags", "Alt text", "Is video", "Duration", "Reactions", "Related pins"],
    views: "2.4K+",
    downloads: "218+",
  },
  {
    id: "apollo-contacts",
    name: "Apollo.io Contacts",
    domain: "apollo.io",
    desc: "Contact emails, phone, title, company, industry, and tech stack",
    category: "Business (B2B)",
    icon: "Ap",
    color: "#6C5CE7",
    fields: ["Name", "Email", "Phone", "Title", "Company", "Industry", "Employees", "Revenue", "Location", "LinkedIn URL", "Technologies", "Funding", "Founded", "Keywords", "Seniority", "Department"],
    views: "2.2K+",
    downloads: "195+",
  },
  {
    id: "g2-reviews",
    name: "G2 Software Reviews",
    domain: "g2.com",
    desc: "Software reviews: ratings, pros, cons, use cases, and company info",
    category: "Business (B2B)",
    icon: "G2",
    color: "#FF492C",
    fields: ["Product name", "Rating", "Review title", "Review text", "Reviewer role", "Company size", "Industry", "Pros", "Cons", "Date", "Verified", "Star breakdown", "Use case", "Alternatives considered", "Recommendations"],
    views: "1.9K+",
    downloads: "167+",
  },
  {
    id: "target-products",
    name: "Target Products",
    domain: "target.com",
    desc: "Price, brand, rating, availability, fulfillment options, and specs",
    category: "E-commerce",
    icon: "◉",
    color: "#CC0000",
    fields: ["TCIN", "Title", "Price", "Sale price", "Brand", "Description", "Rating", "Reviews count", "Category", "Images", "Availability", "Fulfillment", "Same-day delivery", "Size", "Color", "Specifications", "UPC"],
    views: "1.8K+",
    downloads: "155+",
  },
  {
    id: "yelp-businesses",
    name: "Yelp Businesses",
    domain: "yelp.com",
    desc: "Business ratings, reviews, hours, photos, price range, and amenities",
    category: "Business (B2B)",
    icon: "Y",
    color: "#D32323",
    fields: ["Business ID", "Name", "Rating", "Reviews count", "Category", "Price range", "Address", "Phone", "Website", "Hours", "Photos count", "Amenities", "Highlights", "Owner response rate", "Year established", "Health score"],
    views: "1.7K+",
    downloads: "142+",
  },
  {
    id: "zillow-rentals",
    name: "Zillow Rentals",
    domain: "zillow.com",
    desc: "Rent price, deposit, pet policy, amenities, and neighborhood scores",
    category: "Real Estate",
    icon: "Z",
    color: "#006AFF",
    fields: ["Zpid", "Address", "City", "State", "Rent price", "Bedrooms", "Bathrooms", "Living area", "Property type", "Deposit", "Lease term", "Pet policy", "Amenities", "Parking", "Laundry", "Available date", "Contact", "Walk score", "Transit score"],
    views: "1.6K+",
    downloads: "130+",
  },
  {
    id: "realtor-listings",
    name: "Realtor.com Listings",
    domain: "realtor.com",
    desc: "Property price, beds, baths, lot size, agent info, and school data",
    category: "Real Estate",
    icon: "R",
    color: "#D92228",
    fields: ["Property ID", "Address", "Price", "Bedrooms", "Bathrooms", "Sqft", "Lot size", "Year built", "Property type", "Status", "Days on market", "HOA", "Tax", "School district", "Agent", "Broker", "Open houses", "Price history", "Photos"],
    views: "1.5K+",
    downloads: "118+",
  },
  {
    id: "trustpilot-reviews",
    name: "Trustpilot Reviews",
    domain: "trustpilot.com",
    desc: "Company reviews: TrustScore, rating, verified status, and reply data",
    category: "Business (B2B)",
    icon: "★",
    color: "#00B67A",
    fields: ["Company name", "Overall rating", "Review count", "Review title", "Review text", "Rating", "Author", "Date", "Country", "Verified", "Reply text", "Reply date", "Useful count", "Experience date", "Category", "TrustScore"],
    views: "1.5K+",
    downloads: "125+",
  },
  {
    id: "threads-posts",
    name: "Threads Posts",
    domain: "threads.net",
    desc: "Post content, likes, replies, reposts, and author follower count",
    category: "Social Media",
    icon: "@",
    color: "#000000",
    fields: ["Post ID", "Author", "Content", "Date posted", "Likes", "Replies", "Reposts", "Quotes", "Media URLs", "Is reply", "Parent post", "Hashtags", "Mentioned users", "Link preview", "Author followers"],
    views: "1.4K+",
    downloads: "105+",
  },
  {
    id: "upwork-jobs",
    name: "Upwork Job Postings",
    domain: "upwork.com",
    desc: "Budget, skills required, client rating, proposals, and job duration",
    category: "Jobs",
    icon: "U",
    color: "#14A800",
    fields: ["Job ID", "Title", "Description", "Budget", "Hourly rate", "Duration", "Experience level", "Skills", "Category", "Client country", "Client rating", "Client spend", "Proposals", "Posted date", "Connects required", "Remote", "Contract type"],
    views: "1.3K+",
    downloads: "98+",
  },
  {
    id: "telegram-channels",
    name: "Telegram Channels",
    domain: "telegram.org",
    desc: "Channel members, posts, average views, category, and description",
    category: "Social Media",
    icon: "✈",
    color: "#0088CC",
    fields: ["Channel ID", "Title", "Description", "Members count", "Photo URL", "Username", "Invite link", "Recent posts", "Avg views per post", "Category", "Language", "Created date", "Is verified", "Is scam", "Linked chat"],
    views: "1.2K+",
    downloads: "88+",
  },
  {
    id: "bestbuy-products",
    name: "Best Buy Products",
    domain: "bestbuy.com",
    desc: "Price, brand, specs, rating, availability, and open-box pricing",
    category: "E-commerce",
    icon: "BB",
    color: "#0046BE",
    fields: ["SKU", "Title", "Price", "Sale price", "Brand", "Model", "Rating", "Reviews count", "Category", "Description", "Specifications", "Images", "Availability", "Shipping", "Store pickup", "Open box price", "Warranty", "UPC"],
    views: "1.1K+",
    downloads: "82+",
  },
  {
    id: "hacker-news",
    name: "Hacker News",
    domain: "news.ycombinator.com",
    desc: "Story title, score, author, comments, and submission metadata",
    category: "News & Media",
    icon: "Y",
    color: "#FF6600",
    fields: ["ID", "Title", "URL", "Score", "Author", "Comments count", "Date posted", "Type", "Text", "Top comments", "Domain", "Position", "Is dead", "Is deleted"],
    views: "980+",
    downloads: "72+",
  },
  {
    id: "producthunt-products",
    name: "Product Hunt Products",
    domain: "producthunt.com",
    desc: "Upvotes, makers, tagline, topics, pricing type, and launch ranking",
    category: "News & Media",
    icon: "PH",
    color: "#DA552F",
    fields: ["ID", "Name", "Tagline", "Description", "URL", "Upvotes", "Comments count", "Makers", "Topics", "Thumbnail", "Launch date", "Ranking", "Hunter", "Reviews count", "Rating", "Pricing type", "Website"],
    views: "870+",
    downloads: "65+",
  },
  {
    id: "aliexpress-products",
    name: "AliExpress Products",
    domain: "aliexpress.com",
    desc: "Price, discount, orders, store rating, shipping info, and variants",
    category: "E-commerce",
    icon: "Ae",
    color: "#E43225",
    fields: ["Product ID", "Title", "Price", "Original price", "Discount", "Currency", "Orders", "Rating", "Reviews", "Store name", "Store rating", "Ships from", "Free shipping", "Category", "Images", "Variants", "Specifications", "Description"],
    views: "2.1K+",
    downloads: "188+",
  },
  {
    id: "capterra-reviews",
    name: "Capterra Software Reviews",
    domain: "capterra.com",
    desc: "Software ratings, pros, cons, ease of use, and value for money scores",
    category: "Business (B2B)",
    icon: "C",
    color: "#FF9D28",
    fields: ["Product name", "Overall rating", "Review title", "Review text", "Pros", "Cons", "Rating breakdown", "Reviewer role", "Company size", "Industry", "Date", "Likelihood to recommend", "Value for money", "Ease of use", "Customer support"],
    views: "960+",
    downloads: "75+",
  },
];
