/**
 * Full scraper catalog for the library page.
 * All scrapers link to the Bright Data console.
 */

import { AMAZON_SCRAPERS } from "./amazon-scrapers";

export type CatalogScraper = {
  id: string;
  name: string;
  domain: string;
  desc: string;
  category: string;
  icon: string;
  color: string;
  fields: string[];
  views: string;
  downloads: string;
  slug?: string;
  popular?: boolean;
};

export const CATALOG_CATEGORIES = [
  "All",
  "Social Media",
  "E-commerce",
  "Business (B2B)",
  "Jobs",
  "Real Estate",
  "Travel",
  "Search",
  "News & Media",
  "Finance",
] as const;

const DOMAIN_CATEGORY_MAP: Record<string, string> = {
  "linkedin.com": "Business (B2B)",
  "crunchbase.com": "Business (B2B)",
  "glassdoor.com": "Business (B2B)",
  "apollo.io": "Business (B2B)",
  "zoominfo.com": "Business (B2B)",
  "pitchbook.com": "Business (B2B)",
  "dnb.com": "Business (B2B)",
  "g2.com": "Business (B2B)",
  "capterra.com": "Business (B2B)",
  "trustpilot.com": "Business (B2B)",
  "yelp.com": "Business (B2B)",
  "amazon.com": "E-commerce",
  "walmart.com": "E-commerce",
  "ebay.com": "E-commerce",
  "etsy.com": "E-commerce",
  "shopify.com": "E-commerce",
  "target.com": "E-commerce",
  "bestbuy.com": "E-commerce",
  "alibaba.com": "E-commerce",
  "aliexpress.com": "E-commerce",
  "tiktok.com": "Social Media",
  "instagram.com": "Social Media",
  "facebook.com": "Social Media",
  "x.com": "Social Media",
  "twitter.com": "Social Media",
  "youtube.com": "Social Media",
  "reddit.com": "Social Media",
  "pinterest.com": "Social Media",
  "threads.net": "Social Media",
  "telegram.org": "Social Media",
  "discord.com": "Social Media",
  "snapchat.com": "Social Media",
  "indeed.com": "Jobs",
  "glassdoor.com/job": "Jobs",
  "ziprecruiter.com": "Jobs",
  "monster.com": "Jobs",
  "dice.com": "Jobs",
  "upwork.com": "Jobs",
  "fiverr.com": "Jobs",
  "zillow.com": "Real Estate",
  "realtor.com": "Real Estate",
  "redfin.com": "Real Estate",
  "trulia.com": "Real Estate",
  "rightmove.co.uk": "Real Estate",
  "airbnb.com": "Travel",
  "booking.com": "Travel",
  "tripadvisor.com": "Travel",
  "expedia.com": "Travel",
  "hotels.com": "Travel",
  "google.com/maps": "Search",
  "google.com": "Search",
  "bing.com": "Search",
  "finance.yahoo.com": "Finance",
  "bloomberg.com": "Finance",
  "coinmarketcap.com": "Finance",
  "investing.com": "Finance",
  "robinhood.com": "Finance",
  "reuters.com": "News & Media",
  "news.ycombinator.com": "News & Media",
  "techcrunch.com": "News & Media",
  "bbc.com": "News & Media",
  "cnn.com": "News & Media",
  "medium.com": "News & Media",
  "wikipedia.org": "News & Media",
  "substack.com": "News & Media",
  "shopee.com": "E-commerce",
  "temu.com": "E-commerce",
  "shein.com": "E-commerce",
  "wayfair.com": "E-commerce",
  "homedepot.com": "E-commerce",
  "costco.com": "E-commerce",
  "nike.com": "E-commerce",
  "zara.com": "E-commerce",
  "stockx.com": "E-commerce",
  "twitch.tv": "Social Media",
  "quora.com": "Social Media",
  "nextdoor.com": "Social Media",
  "careerbuilder.com": "Jobs",
  "kayak.com": "Travel",
  "skyscanner.com": "Travel",
  "agoda.com": "Travel",
  "vrbo.com": "Travel",
  "zoopla.co.uk": "Real Estate",
  "duckduckgo.com": "Search",
  "openai.com": "Search",
  "clutch.co": "Business (B2B)",
  "wellfound.com": "Business (B2B)",
  "trustradius.com": "Business (B2B)",
};

/**
 * Auto-assign a category based on domain. Falls back to "Search" for unknown domains.
 * Use this when adding new scrapers to avoid manual category guessing.
 */
export function assignCategory(domain: string): string {
  const d = domain.toLowerCase().replace(/^www\./, "");
  for (const [pattern, category] of Object.entries(DOMAIN_CATEGORY_MAP)) {
    if (d === pattern || d.endsWith("." + pattern) || d.startsWith(pattern)) {
      return category;
    }
  }
  return "Search";
}

export const catalog: CatalogScraper[] = [
  {
    id: "linkedin-people",
    name: "LinkedIn People Profiles",
    domain: "linkedin.com",
    desc: "Professional data: name, headline, company, experience, skills, and certifications",
    category: "Business (B2B)",
    icon: "in",
    color: "#0A66C2",
    fields: ["ID", "Name", "City", "Country code", "Position", "About", "Posts", "Current company", "Industry", "Connections", "Education", "Skills", "Certifications", "Languages", "Profile image", "Headline", "Experience years", "Email", "Phone", "Websites", "Recommendations count", "Volunteer experience", "Publications", "Courses", "Honors & awards", "Open to work"],
    views: "118.3K+",
    downloads: "11.1K+",
    slug: "linkedin-profile",
    popular: true,
  },
  {
    id: "amazon-products",
    name: "Amazon Products",
    domain: "amazon.com",
    desc: "Extract prices, reviews, stock levels & seller data from any Amazon product",
    category: "E-commerce",
    icon: "A",
    color: "#FF9900",
    fields: ["Title", "Seller name", "Brand", "Description", "Initial price", "Final price", "Currency", "Availability", "Reviews count", "Rating", "ASIN", "Categories", "Images", "Delivery", "Variations", "Bestseller rank", "Dimensions", "Weight", "Features", "Coupon", "Subscribe & Save", "Frequently bought together", "Color options", "Size options", "Country of origin", "Date first available"],
    views: "34.7K+",
    downloads: "5.7K+",
    slug: "amazon-product",
    popular: true,
  },
  {
    id: "linkedin-companies",
    name: "LinkedIn Company Info",
    domain: "linkedin.com",
    desc: "Company details: industry, size, funding, specialties, and employee count",
    category: "Business (B2B)",
    icon: "in",
    color: "#0A66C2",
    fields: ["ID", "Name", "Country code", "Locations", "Followers", "Employees in LinkedIn", "About", "Specialties", "Industry", "Website", "Founded", "Company size", "Headquarters", "Type", "Logo", "Cover image", "Affiliated companies", "Recent updates", "Job openings count", "Funding info", "Growth rate", "Employee distribution"],
    views: "33K+",
    downloads: "3.5K+",
    popular: true,
  },
  {
    id: "instagram-profiles",
    name: "Instagram Profiles",
    domain: "instagram.com",
    desc: "Followers, posts, bio, engagement rate, recent media, and growth metrics",
    category: "Social Media",
    icon: "◎",
    color: "#E4405F",
    fields: ["Account", "Fbid", "ID", "Followers", "Following", "Posts count", "Is business account", "Is professional account", "Is verified", "Biography", "External URL", "Category", "Profile pic", "Full name", "Engagement rate", "Recent posts", "Story highlights count", "Reels count", "Contact phone", "Contact email", "Business address", "Avg likes per post", "Avg comments per post", "Growth rate 30d"],
    views: "21.9K+",
    downloads: "3.4K+",
    slug: "instagram-profile",
    popular: true,
  },
  {
    id: "crunchbase-companies",
    name: "Crunchbase Companies",
    domain: "crunchbase.com",
    desc: "Startup data: funding rounds, investors, revenue range, and key people",
    category: "Business (B2B)",
    icon: "Cb",
    color: "#0288D1",
    fields: ["Name", "URL", "ID", "Cb rank", "Region", "About", "Industries", "Operating status", "Founded date", "Funding total", "Last funding type", "Employees", "Revenue range", "Website", "Headquarters", "Investors count", "IPO status", "Last funding date", "Acquisitions", "Sub-organizations", "Board members", "Key people", "Technology stack", "Similar companies"],
    views: "15.4K+",
    downloads: "1.6K+",
    popular: true,
  },
  {
    id: "linkedin-jobs",
    name: "LinkedIn Job Listings",
    domain: "linkedin.com",
    desc: "Job title, salary, skills required, company info, and applicant count",
    category: "Jobs",
    icon: "in",
    color: "#0A66C2",
    fields: ["URL", "Job posting id", "Job title", "Company name", "Company id", "Job location", "Job summary", "Job seniority level", "Employment type", "Job function", "Industries", "Applicants count", "Posted date", "Salary range", "Remote allowed", "Skills required", "Benefits", "Company size", "Company followers", "Job description full", "Apply URL", "Referral bonus", "Hiring manager", "Easy apply"],
    views: "15.1K+",
    downloads: "2.2K+",
    popular: true,
  },
  {
    id: "instagram-posts",
    name: "Instagram Posts",
    domain: "instagram.com",
    desc: "Post content, likes, comments, hashtags, engagement rate, and media URLs",
    category: "Social Media",
    icon: "◎",
    color: "#E4405F",
    fields: ["URL", "User posted", "Description", "Hashtags", "Num comments", "Date posted", "Likes", "Photos", "Video URL", "Location", "Tagged users", "Is sponsored", "Engagement rate", "Caption", "Alt text", "Carousel items", "Saves count", "Shares count", "Audio title", "Audio artist", "Filter used", "Aspect ratio", "Is pinned"],
    views: "13K+",
    downloads: "1.6K+",
  },
  {
    id: "google-maps",
    name: "Google Maps Businesses",
    domain: "google.com/maps",
    desc: "Business name, address, phone, ratings, reviews, hours, and photos",
    category: "Search",
    icon: "G",
    color: "#4285F4",
    fields: ["Place id", "URL", "Country", "Name", "Category", "Address", "Description", "Business details", "Phone", "Website", "Rating", "Reviews count", "Opening hours", "Photos", "Latitude", "Longitude", "Price level", "Popular times", "Service options", "Accessibility", "Atmosphere", "Parking", "Payment methods", "Reservation link", "Menu link", "Owner response rate"],
    views: "12.8K+",
    downloads: "1.6K+",
    slug: "google-maps",
    popular: true,
  },
  {
    id: "zillow-listings",
    name: "Zillow Properties",
    domain: "zillow.com",
    desc: "Property price, beds, baths, Zestimate, lot size, and neighborhood scores",
    category: "Real Estate",
    icon: "Z",
    color: "#006AFF",
    fields: ["Zpid", "City", "State", "HomeStatus", "Address", "Bedrooms", "Bathrooms", "Living area", "Lot size", "Price", "Zestimate", "Year built", "Property type", "HOA fee", "Tax assessment", "Price history", "Nearby schools", "Walk score", "Transit score", "Bike score", "Days on Zillow", "Views count", "Saves count", "Agent name", "Agent phone", "Heating", "Cooling", "Flooring"],
    views: "11.9K+",
    downloads: "1.2K+",
    slug: "zillow-listings",
    popular: true,
  },
  {
    id: "linkedin-posts",
    name: "LinkedIn Posts",
    domain: "linkedin.com",
    desc: "Post text, reactions, comments, shares, impressions, and engagement data",
    category: "Social Media",
    icon: "in",
    color: "#0A66C2",
    fields: ["URL", "ID", "User id", "User url", "Title", "Headline", "Post text", "Date posted", "Likes", "Comments", "Shares", "Reactions breakdown", "Media type", "Article URL", "Hashtags", "Mentioned users", "Impressions", "Click-through rate", "Is repost", "Original author", "Follower count at post", "Content type"],
    views: "11.2K+",
    downloads: "1.4K+",
  },
  {
    id: "x-posts",
    name: "X (Twitter) Posts",
    domain: "x.com",
    desc: "Tweet text, likes, retweets, replies, views, and engagement metrics",
    category: "Social Media",
    icon: "𝕏",
    color: "#14171A",
    fields: ["ID", "User posted", "Name", "Description", "Date posted", "Photos", "URL", "Quoted post", "Likes", "Retweets", "Replies", "Bookmarks", "Views", "Is verified", "Language", "Hashtags", "Mentioned users", "Card type", "Poll data", "Thread position", "Source app", "Sensitive content", "Community note", "Engagement rate"],
    views: "10.2K+",
    downloads: "1.2K+",
  },
  {
    id: "tiktok-profiles",
    name: "TikTok Profiles",
    domain: "tiktok.com",
    desc: "Followers, engagement rate, video count, bio, and growth metrics",
    category: "Social Media",
    icon: "♪",
    color: "#00F2EA",
    fields: ["Account id", "Nickname", "Biography", "Avg engagement rate", "Comment engagement rate", "Like engagement rate", "Bio link", "Predicted lang", "Followers", "Following", "Likes", "Videos count", "Verified", "Profile pic", "Region", "Account created", "Avg views per video", "Top hashtags", "Branded content", "Business account", "Category", "Growth rate 30d"],
    views: "8.2K+",
    downloads: "953+",
    slug: "tiktok-posts",
    popular: true,
  },
  {
    id: "youtube-videos",
    name: "YouTube Videos",
    domain: "youtube.com",
    desc: "Title, views, likes, comments, duration, tags, and channel data",
    category: "Social Media",
    icon: "▶",
    color: "#FF0000",
    fields: ["URL", "Title", "Youtuber", "Video url", "Video length", "Likes", "Views", "Comments count", "Description", "Published date", "Thumbnail", "Tags", "Category", "Captions available", "Channel subscribers", "Is live", "Resolution", "Chapters", "End screen links", "Sponsor segments", "Language", "Age restricted", "Premiere date", "Membership only"],
    views: "7.9K+",
    downloads: "708+",
  },
  {
    id: "amazon-reviews",
    name: "Amazon Reviews",
    domain: "amazon.com",
    desc: "Review text, rating, verified purchase status, helpful votes, and author info",
    category: "E-commerce",
    icon: "A",
    color: "#FF9900",
    fields: ["URL", "Product name", "Product rating", "Rating", "Author name", "ASIN", "Review title", "Review text", "Date", "Verified purchase", "Helpful votes", "Images", "Country", "Variant", "Star breakdown", "Review length", "Reviewer rank", "Reviewer badge", "Video review", "Response from seller", "Edition", "Size purchased", "Color purchased"],
    views: "7.2K+",
    downloads: "852+",
    slug: "amazon-reviews",
  },
  {
    id: "tiktok-posts",
    name: "TikTok Posts",
    domain: "tiktok.com",
    desc: "Video metrics: plays, shares, comments, hashtags, and music details",
    category: "Social Media",
    icon: "♪",
    color: "#00F2EA",
    fields: ["URL", "Post id", "Description", "Create time", "Digg count", "Share count", "Collect count", "Comment count", "Play count", "Music title", "Music author", "Hashtags", "Duration", "Is ad", "Author nickname", "Effects", "Stitch enabled", "Duet enabled", "Original sound", "Cover image", "Video quality", "Location tag", "Challenges"],
    views: "6.6K+",
    downloads: "866+",
  },
  {
    id: "facebook-posts",
    name: "Facebook Page Posts",
    domain: "facebook.com",
    desc: "Post content, reactions, comments, shares, media, and audience insights",
    category: "Social Media",
    icon: "f",
    color: "#1877F2",
    fields: ["URL", "Post id", "User url", "Username", "Content", "Date posted", "Hashtags", "Num comments", "Reactions", "Shares", "Photos", "Video URL", "Is sponsored", "Post type", "Link preview", "Reaction breakdown", "Top comments", "Tagged pages", "Check-in location", "Event link", "Audience", "Edited"],
    views: "6.5K+",
    downloads: "623+",
  },
  {
    id: "indeed-jobs",
    name: "Indeed Job Listings",
    domain: "indeed.com",
    desc: "Job title, salary, benefits, qualifications, company rating, and location",
    category: "Jobs",
    icon: "i",
    color: "#2164F3",
    fields: ["Jobid", "Company name", "Date posted", "Job title", "Description text", "Benefits", "Qualifications", "Job type", "Salary", "Location", "Remote", "Experience level", "Education required", "Skills", "Company rating", "Urgently hiring", "Apply link", "Responsive employer", "Hiring multiple", "Schedule", "Supplemental pay", "Work setting", "Industry"],
    views: "6.4K+",
    downloads: "759+",
  },
  {
    id: "walmart-products",
    name: "Walmart Products",
    domain: "walmart.com",
    desc: "Price, brand, rating, availability, shipping options, and specifications",
    category: "E-commerce",
    icon: "W",
    color: "#0071DC",
    fields: ["URL", "Final price", "SKU", "Currency", "GTIN", "Specifications", "Image urls", "Top reviews", "Brand", "Model", "Category", "Availability", "Seller", "Rating", "Reviews count", "Shipping", "Return policy", "Walmart+ eligible", "Rollback price", "Pickup available", "Same-day delivery", "Warranty", "Condition", "Quantity available"],
    views: "5.5K+",
    downloads: "857+",
  },
  {
    id: "tiktok-shop",
    name: "TikTok Shop Products",
    domain: "tiktok.com",
    desc: "Product price, ratings, sold count, shop info, and variant details",
    category: "E-commerce",
    icon: "♪",
    color: "#00F2EA",
    fields: ["URL", "Title", "Available", "Description", "Currency", "Initial price", "Final price", "Discount percent", "Rating", "Reviews count", "Sold count", "Shop name", "Images", "Variants", "Category", "Shipping info", "Return policy", "Shop rating", "Shop followers", "Video reviews", "Size guide", "Material", "Bundle deals"],
    views: "5.3K+",
    downloads: "661+",
  },
  {
    id: "youtube-channels",
    name: "YouTube Channels",
    domain: "youtube.com",
    desc: "Subscribers, total views, upload frequency, country, and channel stats",
    category: "Social Media",
    icon: "▶",
    color: "#FF0000",
    fields: ["URL", "Handle", "Banner img", "Profile image", "Name", "Subscribers", "Description", "Country", "Joined date", "Total views", "Videos count", "Links", "Is verified", "Category", "Average views", "Upload frequency", "Shorts count", "Live streams count", "Community posts", "Memberships available", "Merchandise links", "Playlists count"],
    views: "4.4K+",
    downloads: "502+",
  },
  {
    id: "reddit-posts",
    name: "Reddit Posts",
    domain: "reddit.com",
    desc: "Title, upvotes, comments, awards, community info, and post content",
    category: "Social Media",
    icon: "R",
    color: "#FF4500",
    fields: ["Post id", "URL", "User posted", "Title", "Description", "Num comments", "Date posted", "Community name", "Upvotes", "Downvotes", "Awards", "Is NSFW", "Flair", "Media", "Crosspost", "Top comments", "Upvote ratio", "Is pinned", "Is locked", "Community members", "Author karma", "Post type", "External link"],
    views: "4.4K+",
    downloads: "421+",
  },
  {
    id: "glassdoor-companies",
    name: "Glassdoor Companies",
    domain: "glassdoor.com",
    desc: "Company ratings, CEO approval, salary ranges, benefits, and culture scores",
    category: "Business (B2B)",
    icon: "G",
    color: "#0CAA41",
    fields: ["ID", "Company", "Ratings overall", "Details size", "Details founded", "Details type", "Country code", "Company type", "Revenue", "Industry", "CEO name", "CEO approval", "Recommend to friend", "Culture rating", "Work-life balance", "Benefits rating", "Career opportunities", "Senior management", "Diversity score", "Interview difficulty", "Salary ranges", "Top benefits listed"],
    views: "4.2K+",
    downloads: "378+",
  },
  {
    id: "google-maps-reviews",
    name: "Google Maps Reviews",
    domain: "google.com/maps",
    desc: "Review text, rating, reviewer info, photos, and business response",
    category: "Search",
    icon: "G",
    color: "#4285F4",
    fields: ["URL", "Place id", "Place name", "Country", "Address", "Review id", "Reviewer name", "Reviews by reviewer", "Rating", "Review text", "Date", "Response text", "Photos", "Language", "Is local guide", "Reviewer level", "Visit type", "Meal type", "Price paid", "Service rating", "Food rating", "Atmosphere rating"],
    views: "4.1K+",
    downloads: "299+",
    slug: "google-maps-reviews",
  },
  {
    id: "instagram-reels",
    name: "Instagram Reels",
    domain: "instagram.com",
    desc: "Views, likes, shares, saves, duration, music, and engagement data",
    category: "Social Media",
    icon: "◎",
    color: "#E4405F",
    fields: ["URL", "User posted", "Description", "Hashtags", "Num comments", "Date posted", "Likes", "Views", "Duration", "Music title", "Music artist", "Thumbnail", "Is sponsored", "Location", "Tagged users", "Shares count", "Saves count", "Plays count", "Audio original", "Effect name", "Collab account", "Is remix", "Caption"],
    views: "3.6K+",
    downloads: "435+",
  },
  {
    id: "airbnb-properties",
    name: "Airbnb Properties",
    domain: "airbnb.com",
    desc: "Listing price, location, amenities, reviews, host info, and availability",
    category: "Travel",
    icon: "⌂",
    color: "#FF5A5F",
    fields: ["Name", "Price", "Image", "Description", "Category", "Availability", "Discount", "Reviews", "Rating", "Host name", "Superhost", "Location", "Amenities", "Bedrooms", "Bathrooms", "Max guests", "Check-in", "House rules", "Cancellation policy", "Cleaning fee", "Service fee", "Response rate", "Response time", "Languages spoken", "Neighborhood", "Safety features"],
    views: "3.6K+",
    downloads: "575+",
  },
  {
    id: "x-profiles",
    name: "X (Twitter) Profiles",
    domain: "x.com",
    desc: "Bio, followers, following, tweet count, verification status, and engagement",
    category: "Social Media",
    icon: "𝕏",
    color: "#14171A",
    fields: ["X id", "URL", "ID", "Profile name", "Biography", "Is verified", "Profile image link", "External link", "Followers", "Following", "Tweets count", "Joined date", "Location", "Banner image", "Pinned tweet", "Subscription type", "Verified type", "Professional category", "Lists count", "Spaces hosted", "Average engagement", "Tweet frequency"],
    views: "3.4K+",
    downloads: "220+",
  },
  {
    id: "glassdoor-reviews",
    name: "Glassdoor Reviews",
    domain: "glassdoor.com",
    desc: "Employee reviews: pros, cons, ratings, job title, and management feedback",
    category: "Business (B2B)",
    icon: "G",
    color: "#0CAA41",
    fields: ["Overview id", "Review id", "Review url", "Rating date", "Count helpful", "Employee job title", "Employee length", "Pros", "Cons", "Advice to management", "Overall rating", "Work-life rating", "Culture rating", "Career rating", "Compensation rating", "Senior mgmt rating", "Current employee", "Employment status", "Location", "Recommend", "Business outlook", "CEO opinion"],
    views: "3.3K+",
    downloads: "544+",
  },
  {
    id: "booking-hotels",
    name: "Booking.com Hotels",
    domain: "booking.com",
    desc: "Room prices, ratings, amenities, location, photos, and cancellation policy",
    category: "Travel",
    icon: "B",
    color: "#003580",
    fields: ["URL", "Hotel id", "Title", "Location", "Country", "City", "Metro access", "Images", "Price", "Rating", "Reviews count", "Stars", "Amenities", "Room types", "Free cancellation", "Breakfast included", "Distance to center", "Check-in time", "Check-out time", "Sustainability level", "Genius discount", "Staff rating", "Cleanliness rating", "WiFi rating", "Value rating"],
    views: "3.2K+",
    downloads: "378+",
  },
  {
    id: "yahoo-finance",
    name: "Yahoo Finance",
    domain: "finance.yahoo.com",
    desc: "Stock price, market cap, P/E ratio, earnings, dividends, and analyst ratings",
    category: "Finance",
    icon: "Y",
    color: "#6001D2",
    fields: ["Name", "Company id", "Entity type", "Summary", "Stock ticker", "Currency", "Earnings date", "Exchange", "Market cap", "PE ratio", "52-week high", "52-week low", "Dividend yield", "Revenue", "Profit margin", "Employees", "EPS", "Beta", "Average volume", "Open price", "Previous close", "Day range", "Target price", "Analyst rating"],
    views: "3K+",
    downloads: "351+",
  },
  {
    id: "instagram-comments",
    name: "Instagram Comments",
    domain: "instagram.com",
    desc: "Comment text, likes, replies, author info, and sentiment data",
    category: "Social Media",
    icon: "◎",
    color: "#E4405F",
    fields: ["URL", "Comment user", "Comment user url", "Comment date", "Comment text", "Likes number", "Replies number", "Replies", "Is verified", "User followers", "User profile pic", "Post URL", "Mentioned users", "Hashtags in comment", "Is pinned", "Is creator reply", "Comment language", "Sentiment", "User engagement rate"],
    views: "2.8K+",
    downloads: "320+",
  },
  {
    id: "google-search",
    name: "Google Search Results",
    domain: "google.com",
    desc: "SERP results: titles, URLs, snippets, ads, and rich features",
    category: "Search",
    icon: "G",
    color: "#4285F4",
    fields: ["Query", "Position", "Title", "URL", "Description", "Displayed URL", "Sitelinks", "Knowledge panel", "People also ask", "Related searches", "Featured snippet", "Ads", "Shopping results", "Images", "Videos", "News", "Local pack", "Language", "Country", "Device type", "Total results"],
    views: "9.8K+",
    downloads: "1.1K+",
  },
  {
    id: "ebay-products",
    name: "eBay Products",
    domain: "ebay.com",
    desc: "Price, bids, condition, seller rating, shipping cost, and item specifics",
    category: "E-commerce",
    icon: "e",
    color: "#E53238",
    fields: ["Item ID", "Title", "Price", "Currency", "Condition", "Seller", "Seller rating", "Bids", "Time left", "Shipping cost", "Location", "Returns", "Category", "Brand", "Images", "Watchers", "Sold count", "Item specifics", "Description"],
    views: "4.8K+",
    downloads: "520+",
  },
  {
    id: "etsy-products",
    name: "Etsy Products",
    domain: "etsy.com",
    desc: "Handmade item details: price, shop rating, materials, tags, and reviews",
    category: "E-commerce",
    icon: "E",
    color: "#F56400",
    fields: ["Listing ID", "Title", "Price", "Currency", "Shop name", "Shop rating", "Sales count", "Description", "Tags", "Materials", "Category", "Images", "Reviews count", "Favorites", "Shipping", "Customizable", "Digital download", "Processing time"],
    views: "3.2K+",
    downloads: "310+",
  },
  {
    id: "shopify-products",
    name: "Shopify Store Products",
    domain: "shopify.com",
    desc: "Product catalog: price, variants, inventory, images, and vendor info",
    category: "E-commerce",
    icon: "S",
    color: "#96BF48",
    fields: ["Product ID", "Title", "Handle", "Price", "Compare at price", "Vendor", "Type", "Tags", "Description", "Images", "Variants", "SKU", "Inventory", "Weight", "Published date", "Collection", "Options", "Barcode"],
    views: "2.9K+",
    downloads: "275+",
  },
  {
    id: "tripadvisor-hotels",
    name: "Tripadvisor Hotels",
    domain: "tripadvisor.com",
    desc: "Hotel ratings, price range, amenities, rankings, and traveler reviews",
    category: "Travel",
    icon: "T",
    color: "#00AF87",
    fields: ["Hotel ID", "Name", "Rating", "Reviews count", "Price range", "Location", "Address", "Amenities", "Room types", "Photos", "Ranking", "Awards", "Nearby attractions", "Restaurant count", "Class", "Check-in", "Languages spoken", "Property type"],
    views: "2.7K+",
    downloads: "288+",
  },
  {
    id: "pinterest-pins",
    name: "Pinterest Pins",
    domain: "pinterest.com",
    desc: "Pin images, descriptions, saves, board info, and related content",
    category: "Social Media",
    icon: "P",
    color: "#E60023",
    fields: ["Pin ID", "Title", "Description", "Image URL", "Link", "Board name", "Pinner name", "Saves count", "Comments count", "Domain", "Created at", "Tags", "Alt text", "Is video", "Duration", "Reactions", "Related pins"],
    views: "2.4K+",
    downloads: "218+",
  },
  {
    id: "apollo-contacts",
    name: "Apollo.io Contacts",
    domain: "apollo.io",
    desc: "Contact emails, phone, title, company, industry, and tech stack",
    category: "Business (B2B)",
    icon: "Ap",
    color: "#6C5CE7",
    fields: ["Name", "Email", "Phone", "Title", "Company", "Industry", "Employees", "Revenue", "Location", "LinkedIn URL", "Technologies", "Funding", "Founded", "Keywords", "Seniority", "Department"],
    views: "2.2K+",
    downloads: "195+",
  },
  {
    id: "g2-reviews",
    name: "G2 Software Reviews",
    domain: "g2.com",
    desc: "Software reviews: ratings, pros, cons, use cases, and company info",
    category: "Business (B2B)",
    icon: "G2",
    color: "#FF492C",
    fields: ["Product name", "Rating", "Review title", "Review text", "Reviewer role", "Company size", "Industry", "Pros", "Cons", "Date", "Verified", "Star breakdown", "Use case", "Alternatives considered", "Recommendations"],
    views: "1.9K+",
    downloads: "167+",
  },
  {
    id: "target-products",
    name: "Target Products",
    domain: "target.com",
    desc: "Price, brand, rating, availability, fulfillment options, and specs",
    category: "E-commerce",
    icon: "◉",
    color: "#CC0000",
    fields: ["TCIN", "Title", "Price", "Sale price", "Brand", "Description", "Rating", "Reviews count", "Category", "Images", "Availability", "Fulfillment", "Same-day delivery", "Size", "Color", "Specifications", "UPC"],
    views: "1.8K+",
    downloads: "155+",
  },
  {
    id: "yelp-businesses",
    name: "Yelp Businesses",
    domain: "yelp.com",
    desc: "Business ratings, reviews, hours, photos, price range, and amenities",
    category: "Business (B2B)",
    icon: "Y",
    color: "#D32323",
    fields: ["Business ID", "Name", "Rating", "Reviews count", "Category", "Price range", "Address", "Phone", "Website", "Hours", "Photos count", "Amenities", "Highlights", "Owner response rate", "Year established", "Health score"],
    views: "1.7K+",
    downloads: "142+",
  },
  {
    id: "zillow-rentals",
    name: "Zillow Rentals",
    domain: "zillow.com",
    desc: "Rent price, deposit, pet policy, amenities, and neighborhood scores",
    category: "Real Estate",
    icon: "Z",
    color: "#006AFF",
    fields: ["Zpid", "Address", "City", "State", "Rent price", "Bedrooms", "Bathrooms", "Living area", "Property type", "Deposit", "Lease term", "Pet policy", "Amenities", "Parking", "Laundry", "Available date", "Contact", "Walk score", "Transit score"],
    views: "1.6K+",
    downloads: "130+",
  },
  {
    id: "realtor-listings",
    name: "Realtor.com Listings",
    domain: "realtor.com",
    desc: "Property price, beds, baths, lot size, agent info, and school data",
    category: "Real Estate",
    icon: "R",
    color: "#D92228",
    fields: ["Property ID", "Address", "Price", "Bedrooms", "Bathrooms", "Sqft", "Lot size", "Year built", "Property type", "Status", "Days on market", "HOA", "Tax", "School district", "Agent", "Broker", "Open houses", "Price history", "Photos"],
    views: "1.5K+",
    downloads: "118+",
  },
  {
    id: "trustpilot-reviews",
    name: "Trustpilot Reviews",
    domain: "trustpilot.com",
    desc: "Company reviews: TrustScore, rating, verified status, and reply data",
    category: "Business (B2B)",
    icon: "★",
    color: "#00B67A",
    fields: ["Company name", "Overall rating", "Review count", "Review title", "Review text", "Rating", "Author", "Date", "Country", "Verified", "Reply text", "Reply date", "Useful count", "Experience date", "Category", "TrustScore"],
    views: "1.5K+",
    downloads: "125+",
  },
  {
    id: "threads-posts",
    name: "Threads Posts",
    domain: "threads.net",
    desc: "Post content, likes, replies, reposts, and author follower count",
    category: "Social Media",
    icon: "@",
    color: "#000000",
    fields: ["Post ID", "Author", "Content", "Date posted", "Likes", "Replies", "Reposts", "Quotes", "Media URLs", "Is reply", "Parent post", "Hashtags", "Mentioned users", "Link preview", "Author followers"],
    views: "1.4K+",
    downloads: "105+",
  },
  {
    id: "upwork-jobs",
    name: "Upwork Job Postings",
    domain: "upwork.com",
    desc: "Budget, skills required, client rating, proposals, and job duration",
    category: "Jobs",
    icon: "U",
    color: "#14A800",
    fields: ["Job ID", "Title", "Description", "Budget", "Hourly rate", "Duration", "Experience level", "Skills", "Category", "Client country", "Client rating", "Client spend", "Proposals", "Posted date", "Connects required", "Remote", "Contract type"],
    views: "1.3K+",
    downloads: "98+",
  },
  {
    id: "telegram-channels",
    name: "Telegram Channels",
    domain: "telegram.org",
    desc: "Channel members, posts, average views, category, and description",
    category: "Social Media",
    icon: "✈",
    color: "#0088CC",
    fields: ["Channel ID", "Title", "Description", "Members count", "Photo URL", "Username", "Invite link", "Recent posts", "Avg views per post", "Category", "Language", "Created date", "Is verified", "Is scam", "Linked chat"],
    views: "1.2K+",
    downloads: "88+",
  },
  {
    id: "bestbuy-products",
    name: "Best Buy Products",
    domain: "bestbuy.com",
    desc: "Price, brand, specs, rating, availability, and open-box pricing",
    category: "E-commerce",
    icon: "BB",
    color: "#0046BE",
    fields: ["SKU", "Title", "Price", "Sale price", "Brand", "Model", "Rating", "Reviews count", "Category", "Description", "Specifications", "Images", "Availability", "Shipping", "Store pickup", "Open box price", "Warranty", "UPC"],
    views: "1.1K+",
    downloads: "82+",
  },
  {
    id: "hacker-news",
    name: "Hacker News",
    domain: "news.ycombinator.com",
    desc: "Story title, score, author, comments, and submission metadata",
    category: "News & Media",
    icon: "Y",
    color: "#FF6600",
    fields: ["ID", "Title", "URL", "Score", "Author", "Comments count", "Date posted", "Type", "Text", "Top comments", "Domain", "Position", "Is dead", "Is deleted"],
    views: "980+",
    downloads: "72+",
  },
  {
    id: "producthunt-products",
    name: "Product Hunt Products",
    domain: "producthunt.com",
    desc: "Upvotes, makers, tagline, topics, pricing type, and launch ranking",
    category: "News & Media",
    icon: "PH",
    color: "#DA552F",
    fields: ["ID", "Name", "Tagline", "Description", "URL", "Upvotes", "Comments count", "Makers", "Topics", "Thumbnail", "Launch date", "Ranking", "Hunter", "Reviews count", "Rating", "Pricing type", "Website"],
    views: "870+",
    downloads: "65+",
  },
  {
    id: "aliexpress-products",
    name: "AliExpress Products",
    domain: "aliexpress.com",
    desc: "Price, discount, orders, store rating, shipping info, and variants",
    category: "E-commerce",
    icon: "Ae",
    color: "#E43225",
    fields: ["Product ID", "Title", "Price", "Original price", "Discount", "Currency", "Orders", "Rating", "Reviews", "Store name", "Store rating", "Ships from", "Free shipping", "Category", "Images", "Variants", "Specifications", "Description"],
    views: "2.1K+",
    downloads: "188+",
  },
  {
    id: "capterra-reviews",
    name: "Capterra Software Reviews",
    domain: "capterra.com",
    desc: "Software ratings, pros, cons, ease of use, and value for money scores",
    category: "Business (B2B)",
    icon: "C",
    color: "#FF9D28",
    fields: ["Product name", "Overall rating", "Review title", "Review text", "Pros", "Cons", "Rating breakdown", "Reviewer role", "Company size", "Industry", "Date", "Likelihood to recommend", "Value for money", "Ease of use", "Customer support"],
    views: "960+",
    downloads: "75+",
  },

  // ─── Additional 50 popular scrapers ───────────────────────────────────────────

  {
    id: "shopee-products",
    name: "Shopee Products",
    domain: "shopee.com",
    desc: "Product price, ratings, sold count, shop info, flash sale, and variants",
    category: "E-commerce",
    icon: "Sh",
    color: "#EE4D2D",
    fields: ["Product ID", "Title", "Price", "Original price", "Discount", "Currency", "Sold count", "Rating", "Reviews count", "Shop name", "Shop rating", "Category", "Images", "Variants", "Description", "Ships from", "Free shipping", "Flash sale", "Vouchers", "Stock", "Brand", "COD available"],
    views: "4.1K+",
    downloads: "490+",
  },
  {
    id: "alibaba-products",
    name: "Alibaba Products",
    domain: "alibaba.com",
    desc: "B2B supplier products: MOQ, pricing tiers, certifications, and trade assurance",
    category: "E-commerce",
    icon: "Al",
    color: "#FF6A00",
    fields: ["Product ID", "Title", "Price range", "MOQ", "Supplier", "Supplier rating", "Years on platform", "Trade assurance", "Certifications", "Category", "Images", "Shipping", "Lead time", "Payment methods", "Response rate", "Transaction history", "Customization", "Sample available"],
    views: "3.8K+",
    downloads: "415+",
  },
  {
    id: "shein-products",
    name: "Shein Products",
    domain: "shein.com",
    desc: "Fast fashion items: price, discount, ratings, size availability, and trends",
    category: "E-commerce",
    icon: "SH",
    color: "#222222",
    fields: ["Product ID", "Title", "Price", "Original price", "Discount", "Rating", "Reviews count", "Sold count", "Category", "Color options", "Size options", "Images", "Description", "Material", "Care instructions", "Model info", "Style tags", "New arrival", "Trending"],
    views: "2.9K+",
    downloads: "340+",
  },
  {
    id: "temu-products",
    name: "Temu Products",
    domain: "temu.com",
    desc: "Ultra-value products: price, sold count, reviews, and shipping estimates",
    category: "E-commerce",
    icon: "Te",
    color: "#FB7701",
    fields: ["Product ID", "Title", "Price", "Original price", "Discount percent", "Sold count", "Rating", "Reviews", "Category", "Images", "Variants", "Description", "Shipping estimate", "Return policy", "Seller", "Flash deal", "Coupon eligible", "Bundle deals"],
    views: "2.5K+",
    downloads: "295+",
  },
  {
    id: "wayfair-products",
    name: "Wayfair Products",
    domain: "wayfair.com",
    desc: "Furniture and home goods: price, dimensions, materials, and customer photos",
    category: "E-commerce",
    icon: "Wf",
    color: "#7B2D8B",
    fields: ["SKU", "Title", "Price", "Sale price", "Brand", "Rating", "Reviews count", "Category", "Dimensions", "Material", "Color", "Weight", "Images", "Customer photos", "Assembly required", "Shipping", "Return policy", "In stock", "Room type", "Style"],
    views: "1.8K+",
    downloads: "195+",
  },
  {
    id: "homedepot-products",
    name: "Home Depot Products",
    domain: "homedepot.com",
    desc: "Home improvement products: price, specs, availability, and installation services",
    category: "E-commerce",
    icon: "HD",
    color: "#F96302",
    fields: ["Product ID", "Title", "Price", "Brand", "Model", "Rating", "Reviews count", "Category", "Specifications", "Images", "Availability", "Store pickup", "Delivery", "Installation available", "Warranty", "Dimensions", "Weight", "Material", "Color/Finish", "UPC"],
    views: "1.6K+",
    downloads: "175+",
  },
  {
    id: "costco-products",
    name: "Costco Products",
    domain: "costco.com",
    desc: "Wholesale products: member price, non-member price, item limit, and specs",
    category: "E-commerce",
    icon: "Co",
    color: "#E31837",
    fields: ["Item number", "Title", "Price", "Member price", "Brand", "Rating", "Reviews count", "Category", "Description", "Images", "Specifications", "Shipping included", "Delivery estimate", "Item limit", "Warehouse only", "Online only", "Weight", "Country of origin"],
    views: "1.4K+",
    downloads: "152+",
  },
  {
    id: "nike-products",
    name: "Nike Products",
    domain: "nike.com",
    desc: "Sneakers and apparel: price, colorways, sizes, athlete editions, and stock",
    category: "E-commerce",
    icon: "N",
    color: "#111111",
    fields: ["Style code", "Title", "Subtitle", "Price", "Sale price", "Category", "Color", "Available sizes", "Images", "Description", "Material", "Technology", "Rating", "Reviews count", "Release date", "Exclusive access", "Customizable", "Gender", "Sport", "Collection"],
    views: "1.3K+",
    downloads: "138+",
  },
  {
    id: "zara-products",
    name: "Zara Products",
    domain: "zara.com",
    desc: "Fashion items: price, materials, care, available sizes, and collection info",
    category: "E-commerce",
    icon: "Za",
    color: "#000000",
    fields: ["Product ID", "Title", "Price", "Category", "Color", "Sizes available", "Images", "Description", "Material composition", "Care instructions", "Model info", "Collection", "New arrival", "Limited edition", "Country of origin", "Sustainability label"],
    views: "1.1K+",
    downloads: "115+",
  },
  {
    id: "stockx-products",
    name: "StockX Products",
    domain: "stockx.com",
    desc: "Sneaker and streetwear resale: last sale, bid/ask, price history, and volatility",
    category: "E-commerce",
    icon: "SX",
    color: "#006340",
    fields: ["Product ID", "Title", "Brand", "Last sale", "Lowest ask", "Highest bid", "Category", "Colorway", "Retail price", "Release date", "Style code", "Images", "Price history", "Number of sales", "Volatility", "Trade range", "Deadstock", "Size", "Condition"],
    views: "1.5K+",
    downloads: "162+",
  },
  {
    id: "twitch-channels",
    name: "Twitch Channels",
    domain: "twitch.tv",
    desc: "Streamer data: followers, avg viewers, schedule, game categories, and subs",
    category: "Social Media",
    icon: "Tw",
    color: "#9146FF",
    fields: ["Channel ID", "Display name", "Followers", "Total views", "Average viewers", "Peak viewers", "Game categories", "Language", "Schedule", "Partner status", "Description", "Profile image", "Banner", "Social links", "Stream title", "Subscriber count", "Emotes", "Created date", "Last stream date", "Chat mode"],
    views: "2.2K+",
    downloads: "248+",
  },
  {
    id: "discord-servers",
    name: "Discord Servers",
    domain: "discord.com",
    desc: "Server info: member count, channels, boosts, categories, and activity level",
    category: "Social Media",
    icon: "Dc",
    color: "#5865F2",
    fields: ["Server ID", "Name", "Description", "Member count", "Online count", "Channels", "Categories", "Boost level", "Icon", "Banner", "Invite URL", "Created date", "Verification level", "Features", "Roles count", "Emojis count", "Activity level", "Owner"],
    views: "1.4K+",
    downloads: "125+",
  },
  {
    id: "quora-answers",
    name: "Quora Answers",
    domain: "quora.com",
    desc: "Questions, top answers, author credentials, upvotes, and topic data",
    category: "Social Media",
    icon: "Q",
    color: "#B92B27",
    fields: ["Question ID", "Question text", "Answer ID", "Answer text", "Author name", "Author credentials", "Upvotes", "Comments count", "Date answered", "Views", "Topic", "Related questions", "Is top answer", "Author followers", "Shares", "Spaces", "Language"],
    views: "1.6K+",
    downloads: "145+",
  },
  {
    id: "medium-articles",
    name: "Medium Articles",
    domain: "medium.com",
    desc: "Article content, claps, responses, reading time, and publication info",
    category: "News & Media",
    icon: "M",
    color: "#000000",
    fields: ["Article ID", "Title", "Subtitle", "Author", "Publication", "Content", "Claps", "Responses", "Reading time", "Date published", "Tags", "URL", "Image", "Is member only", "Followers of author", "Author bio", "Related articles", "Word count", "Language"],
    views: "1.8K+",
    downloads: "168+",
  },
  {
    id: "nextdoor-posts",
    name: "Nextdoor Posts",
    domain: "nextdoor.com",
    desc: "Neighborhood posts: reactions, comments, categories, and local business mentions",
    category: "Social Media",
    icon: "Nd",
    color: "#8ED500",
    fields: ["Post ID", "Author", "Neighborhood", "Content", "Date posted", "Reactions", "Comments count", "Category", "Photos", "Business mentioned", "Event info", "Is sponsored", "Replies", "Location", "Verified neighbor"],
    views: "780+",
    downloads: "62+",
  },
  {
    id: "ziprecruiter-jobs",
    name: "ZipRecruiter Jobs",
    domain: "ziprecruiter.com",
    desc: "Job listings: salary estimate, skills match score, and easy apply status",
    category: "Jobs",
    icon: "Zr",
    color: "#25C764",
    fields: ["Job ID", "Title", "Company", "Location", "Salary estimate", "Job type", "Posted date", "Description", "Skills required", "Experience level", "Education", "Benefits", "Match score", "Easy apply", "Remote", "Urgently hiring", "Company rating", "Industry"],
    views: "1.8K+",
    downloads: "195+",
  },
  {
    id: "monster-jobs",
    name: "Monster Jobs",
    domain: "monster.com",
    desc: "Job postings: salary, experience level, company info, and application details",
    category: "Jobs",
    icon: "Mo",
    color: "#6E45A5",
    fields: ["Job ID", "Title", "Company", "Location", "Salary range", "Job type", "Posted date", "Description", "Requirements", "Benefits", "Experience level", "Education", "Skills", "Apply URL", "Industry", "Company size", "Remote options"],
    views: "1.4K+",
    downloads: "148+",
  },
  {
    id: "dice-jobs",
    name: "Dice Tech Jobs",
    domain: "dice.com",
    desc: "Tech job listings: skills, salary, remote status, and employer tech stack",
    category: "Jobs",
    icon: "Di",
    color: "#EB1C26",
    fields: ["Job ID", "Title", "Company", "Location", "Salary range", "Posted date", "Skills", "Employment type", "Experience level", "Remote", "Description", "Tech stack", "Industry", "Visa sponsor", "Travel required", "Clearance required", "Contract length"],
    views: "1.2K+",
    downloads: "110+",
  },
  {
    id: "fiverr-services",
    name: "Fiverr Services",
    domain: "fiverr.com",
    desc: "Freelance gigs: price tiers, seller rating, delivery time, and reviews",
    category: "Jobs",
    icon: "Fi",
    color: "#1DBF73",
    fields: ["Gig ID", "Title", "Seller name", "Seller level", "Rating", "Reviews count", "Starting price", "Category", "Subcategory", "Delivery time", "Revisions", "Description", "Tags", "Images", "Orders in queue", "Response time", "Languages", "Pro verified", "Packages"],
    views: "1.9K+",
    downloads: "210+",
  },
  {
    id: "careerbuilder-jobs",
    name: "CareerBuilder Jobs",
    domain: "careerbuilder.com",
    desc: "Job postings with salary data, company reviews, and skills assessments",
    category: "Jobs",
    icon: "CB",
    color: "#0075CF",
    fields: ["Job ID", "Title", "Company", "Location", "Salary range", "Job type", "Posted date", "Description", "Requirements", "Education", "Experience", "Skills", "Benefits", "Apply URL", "Company rating", "Industry", "Remote", "Travel percent"],
    views: "1.0K+",
    downloads: "92+",
  },
  {
    id: "expedia-hotels",
    name: "Expedia Hotels",
    domain: "expedia.com",
    desc: "Hotel pricing, guest ratings, amenities, room types, and cancellation policy",
    category: "Travel",
    icon: "Ex",
    color: "#00355F",
    fields: ["Hotel ID", "Name", "Location", "Star rating", "Guest rating", "Reviews count", "Price per night", "Room types", "Amenities", "Photos", "Distance to center", "Free cancellation", "Breakfast included", "Pool", "Parking", "WiFi", "Pet friendly", "Check-in time", "Loyalty points", "VIP access"],
    views: "2.4K+",
    downloads: "275+",
  },
  {
    id: "hotels-com",
    name: "Hotels.com Properties",
    domain: "hotels.com",
    desc: "Hotel listings: price, rewards nights, guest reviews, and neighborhood info",
    category: "Travel",
    icon: "H",
    color: "#D32F2F",
    fields: ["Property ID", "Name", "Location", "Star class", "Guest rating", "Reviews count", "Price per night", "Rewards eligible", "Room types", "Amenities", "Photos", "Neighborhood", "Landmarks nearby", "Free cancellation", "Breakfast", "Pay later", "Member price", "Accessibility"],
    views: "1.8K+",
    downloads: "195+",
  },
  {
    id: "kayak-flights",
    name: "Kayak Flights",
    domain: "kayak.com",
    desc: "Flight prices, airlines, layovers, duration, and price forecast data",
    category: "Travel",
    icon: "K",
    color: "#FF690F",
    fields: ["Flight ID", "Airline", "Origin", "Destination", "Departure time", "Arrival time", "Duration", "Stops", "Price", "Cabin class", "Aircraft", "Layover cities", "Baggage included", "CO2 emissions", "Price forecast", "Best time to buy", "Alliance", "Booking URL"],
    views: "2.1K+",
    downloads: "235+",
  },
  {
    id: "skyscanner-flights",
    name: "Skyscanner Flights",
    domain: "skyscanner.com",
    desc: "Flight search results: cheapest, fastest, and best-value route options",
    category: "Travel",
    icon: "Sk",
    color: "#0770E3",
    fields: ["Route ID", "Airline", "Origin", "Destination", "Outbound time", "Return time", "Duration", "Stops", "Price", "Currency", "Cabin class", "Rating", "Direct", "Baggage", "Self transfer", "Booking agent", "Price alert", "Flexible dates"],
    views: "1.9K+",
    downloads: "212+",
  },
  {
    id: "agoda-hotels",
    name: "Agoda Hotels",
    domain: "agoda.com",
    desc: "Asia-focused hotel deals: insider pricing, reviews, and property features",
    category: "Travel",
    icon: "Ag",
    color: "#5542F6",
    fields: ["Hotel ID", "Name", "Location", "Country", "Star rating", "Review score", "Reviews count", "Price", "Insider deal", "Room types", "Amenities", "Photos", "Distance to center", "Free cancellation", "Breakfast", "Airport shuttle", "Check-in time", "Languages spoken"],
    views: "1.5K+",
    downloads: "165+",
  },
  {
    id: "vrbo-properties",
    name: "Vrbo Properties",
    domain: "vrbo.com",
    desc: "Vacation rentals: nightly rate, amenities, guest capacity, and availability",
    category: "Travel",
    icon: "Vr",
    color: "#3D67FF",
    fields: ["Property ID", "Title", "Location", "Nightly rate", "Total price", "Bedrooms", "Bathrooms", "Sleeps", "Rating", "Reviews count", "Amenities", "Photos", "House rules", "Cancellation policy", "Check-in", "Owner info", "Response rate", "Minimum stay", "Pet friendly", "Pool"],
    views: "1.3K+",
    downloads: "142+",
  },
  {
    id: "redfin-listings",
    name: "Redfin Listings",
    domain: "redfin.com",
    desc: "Property listings: Redfin estimate, HOT homes badge, and market insights",
    category: "Real Estate",
    icon: "Rf",
    color: "#A02021",
    fields: ["Property ID", "Address", "Price", "Redfin estimate", "Beds", "Baths", "Sqft", "Lot size", "Year built", "Property type", "Status", "Days on market", "HOT home", "Price/sqft", "HOA", "Parking", "School district", "Walk score", "Agent", "Open house", "Price history", "Tax history"],
    views: "1.7K+",
    downloads: "185+",
  },
  {
    id: "trulia-properties",
    name: "Trulia Properties",
    domain: "trulia.com",
    desc: "Listings with neighborhood insights, crime data, commute times, and schools",
    category: "Real Estate",
    icon: "Tr",
    color: "#4EA85E",
    fields: ["Property ID", "Address", "Price", "Beds", "Baths", "Sqft", "Year built", "Property type", "Status", "Days on market", "HOA", "Neighborhood", "Crime grade", "Schools grade", "Commute score", "Shops & restaurants", "Agent", "Open house", "Price history", "Photos", "Description"],
    views: "1.3K+",
    downloads: "135+",
  },
  {
    id: "rightmove-properties",
    name: "Rightmove Properties",
    domain: "rightmove.co.uk",
    desc: "UK property listings: price, council tax band, EPC rating, and floorplan",
    category: "Real Estate",
    icon: "Rm",
    color: "#00DEB6",
    fields: ["Property ID", "Address", "Price", "Price qualifier", "Beds", "Baths", "Receptions", "Property type", "Tenure", "Council tax band", "EPC rating", "Agent", "Description", "Photos", "Floorplan", "Date listed", "Key features", "Nearest stations", "Broadband speed", "Chain free"],
    views: "2.0K+",
    downloads: "220+",
  },
  {
    id: "zoopla-properties",
    name: "Zoopla Properties",
    domain: "zoopla.co.uk",
    desc: "UK property listings: Zed-Index estimate, price history, and local area stats",
    category: "Real Estate",
    icon: "Zp",
    color: "#8046F3",
    fields: ["Property ID", "Address", "Price", "Zed-Index", "Beds", "Baths", "Property type", "Tenure", "Agent", "Description", "Photos", "Floorplan", "EPC rating", "Date listed", "Price history", "Area stats", "Nearest stations", "Schools nearby", "Council tax band"],
    views: "1.5K+",
    downloads: "155+",
  },
  {
    id: "bing-search",
    name: "Bing Search Results",
    domain: "bing.com",
    desc: "SERP data: organic results, ads, related searches, and knowledge panel",
    category: "Search",
    icon: "B",
    color: "#008373",
    fields: ["Query", "Position", "Title", "URL", "Description", "Displayed URL", "Sitelinks", "Knowledge panel", "Related searches", "Ads", "Images", "Videos", "News", "Shopping", "Local results", "Language", "Country", "Total results", "Copilot answer"],
    views: "2.8K+",
    downloads: "310+",
  },
  {
    id: "google-shopping",
    name: "Google Shopping Results",
    domain: "google.com",
    desc: "Product listings: price comparisons, merchant ratings, and shipping info",
    category: "E-commerce",
    icon: "G",
    color: "#4285F4",
    fields: ["Query", "Position", "Title", "Price", "Currency", "Merchant", "Merchant rating", "URL", "Image", "Shipping cost", "Free shipping", "Condition", "Sale price", "Star rating", "Reviews count", "In stock", "Delivery estimate", "Returns policy"],
    views: "3.2K+",
    downloads: "365+",
  },
  {
    id: "chatgpt-conversations",
    name: "ChatGPT Conversations",
    domain: "openai.com",
    desc: "AI conversation data: prompts, responses, model version, and token usage",
    category: "Search",
    icon: "AI",
    color: "#10A37F",
    fields: ["Conversation ID", "Title", "Prompt", "Response", "Model", "Date", "Token count", "Plugins used", "Code blocks", "Language", "Turn count", "Shared link", "Category", "Custom instructions", "System prompt"],
    views: "3.5K+",
    downloads: "395+",
  },
  {
    id: "duckduckgo-search",
    name: "DuckDuckGo Search",
    domain: "duckduckgo.com",
    desc: "Privacy-focused search results: organic listings, instant answers, and topics",
    category: "Search",
    icon: "DD",
    color: "#DE5833",
    fields: ["Query", "Position", "Title", "URL", "Description", "Instant answer", "Related topics", "Images", "Videos", "News", "Ads", "Language", "Region", "Safe search", "Total results"],
    views: "1.4K+",
    downloads: "130+",
  },
  {
    id: "zoominfo-contacts",
    name: "ZoomInfo Contacts",
    domain: "zoominfo.com",
    desc: "B2B contact data: verified emails, direct dials, org chart, and intent signals",
    category: "Business (B2B)",
    icon: "Zi",
    color: "#5849BC",
    fields: ["Contact ID", "Name", "Email", "Direct dial", "Mobile", "Title", "Seniority", "Department", "Company", "Company revenue", "Company size", "Industry", "Location", "LinkedIn URL", "Technologies", "Intent signals", "Org chart position", "Last verified"],
    views: "2.6K+",
    downloads: "285+",
  },
  {
    id: "clutch-agencies",
    name: "Clutch.co Agencies",
    domain: "clutch.co",
    desc: "B2B service providers: ratings, reviews, project size, and client list",
    category: "Business (B2B)",
    icon: "Cl",
    color: "#FF3D2E",
    fields: ["Company ID", "Name", "Rating", "Reviews count", "Location", "Employees", "Hourly rate", "Min project size", "Services", "Industries", "Clients", "Founded", "Description", "Verified", "Portfolio", "Awards", "Clutch rank"],
    views: "1.2K+",
    downloads: "105+",
  },
  {
    id: "wellfound-startups",
    name: "Wellfound Startups",
    domain: "wellfound.com",
    desc: "Startup profiles: funding, team size, open roles, and investor list",
    category: "Business (B2B)",
    icon: "Wf",
    color: "#000000",
    fields: ["Company ID", "Name", "Description", "Stage", "Funding total", "Funding rounds", "Investors", "Team size", "Location", "Markets", "Open jobs", "Website", "Founded", "Signal score", "Logo", "Tech stack", "Hiring status"],
    views: "1.1K+",
    downloads: "95+",
  },
  {
    id: "trustradius-reviews",
    name: "TrustRadius Reviews",
    domain: "trustradius.com",
    desc: "Enterprise software reviews: trScore, detailed ratings, and buyer insights",
    category: "Business (B2B)",
    icon: "TR",
    color: "#333F48",
    fields: ["Product name", "trScore", "Rating", "Review title", "Review text", "Pros", "Cons", "Reviewer role", "Company size", "Industry", "Use case", "Date", "Verified", "Alternatives evaluated", "Implementation time", "ROI score", "Support rating"],
    views: "880+",
    downloads: "72+",
  },
  {
    id: "pitchbook-companies",
    name: "PitchBook Companies",
    domain: "pitchbook.com",
    desc: "VC-backed companies: valuations, investors, deal history, and comparables",
    category: "Business (B2B)",
    icon: "PB",
    color: "#003B5C",
    fields: ["Company ID", "Name", "Description", "Valuation", "Last funding", "Total raised", "Investors", "Stage", "Founded", "Employees", "Revenue", "Industry", "Headquarters", "Key people", "Board members", "Comparable companies", "Exit status", "Deal history"],
    views: "1.0K+",
    downloads: "88+",
  },
  {
    id: "coinmarketcap-crypto",
    name: "CoinMarketCap Crypto",
    domain: "coinmarketcap.com",
    desc: "Cryptocurrency data: price, market cap, volume, supply, and historical charts",
    category: "Finance",
    icon: "₿",
    color: "#17181B",
    fields: ["Coin ID", "Name", "Symbol", "Price", "Market cap", "Volume 24h", "Change 24h", "Change 7d", "Circulating supply", "Max supply", "Rank", "ATH", "ATH date", "ATL", "Exchange listings", "Category", "Platform", "Contract address", "Dominance"],
    views: "3.1K+",
    downloads: "350+",
  },
  {
    id: "investing-com-stocks",
    name: "Investing.com Stocks",
    domain: "investing.com",
    desc: "Stock quotes, technical indicators, financials, analyst consensus, and news",
    category: "Finance",
    icon: "Iv",
    color: "#143E5B",
    fields: ["Symbol", "Name", "Price", "Change", "Change %", "Volume", "Market cap", "P/E ratio", "EPS", "Dividend yield", "52-week high", "52-week low", "Technical rating", "Moving averages", "RSI", "Revenue", "Net income", "Analyst target", "Consensus", "Next earnings date"],
    views: "2.2K+",
    downloads: "245+",
  },
  {
    id: "bloomberg-articles",
    name: "Bloomberg News",
    domain: "bloomberg.com",
    desc: "Financial news articles: headlines, market impact, sectors, and author analysis",
    category: "Finance",
    icon: "Bl",
    color: "#000000",
    fields: ["Article ID", "Title", "Summary", "Content", "Author", "Published date", "Category", "Tags", "Tickers mentioned", "Market impact", "Region", "URL", "Images", "Related articles", "Premium content", "Word count"],
    views: "1.6K+",
    downloads: "155+",
  },
  {
    id: "robinhood-stocks",
    name: "Robinhood Stocks",
    domain: "robinhood.com",
    desc: "Stock data: price, popularity ranking, analyst ratings, and earnings",
    category: "Finance",
    icon: "Rh",
    color: "#00C805",
    fields: ["Symbol", "Name", "Price", "Change", "Change %", "Market cap", "P/E ratio", "Dividend yield", "52-week high", "52-week low", "Volume", "Avg volume", "Popularity rank", "Holders count", "Analyst rating", "Price target", "Earnings date", "Sector", "Industry", "IPO date"],
    views: "1.3K+",
    downloads: "125+",
  },
  {
    id: "reuters-articles",
    name: "Reuters News",
    domain: "reuters.com",
    desc: "Global news: articles, category, region, market data references, and topics",
    category: "News & Media",
    icon: "Re",
    color: "#FF8000",
    fields: ["Article ID", "Title", "Summary", "Content", "Author", "Published date", "Category", "Region", "Tags", "URL", "Images", "Related articles", "Tickers mentioned", "Source", "Language", "Word count", "Updated date"],
    views: "1.5K+",
    downloads: "148+",
  },
  {
    id: "techcrunch-articles",
    name: "TechCrunch Articles",
    domain: "techcrunch.com",
    desc: "Startup and tech news: funding announcements, product launches, and analysis",
    category: "News & Media",
    icon: "TC",
    color: "#0A9E01",
    fields: ["Article ID", "Title", "Summary", "Content", "Author", "Published date", "Category", "Tags", "Companies mentioned", "Funding amount", "URL", "Images", "Comments count", "Related articles", "Series", "Word count"],
    views: "1.3K+",
    downloads: "118+",
  },
  {
    id: "bbc-news",
    name: "BBC News Articles",
    domain: "bbc.com",
    desc: "World news coverage: articles, topics, regions, and multimedia content",
    category: "News & Media",
    icon: "BBC",
    color: "#BB1919",
    fields: ["Article ID", "Title", "Summary", "Content", "Author", "Published date", "Category", "Region", "Topics", "URL", "Images", "Video", "Related stories", "Live coverage", "Language", "Last updated"],
    views: "1.4K+",
    downloads: "132+",
  },
  {
    id: "cnn-articles",
    name: "CNN News Articles",
    domain: "cnn.com",
    desc: "Breaking news and analysis: articles, live updates, video transcripts",
    category: "News & Media",
    icon: "CNN",
    color: "#CC0000",
    fields: ["Article ID", "Title", "Summary", "Content", "Author", "Published date", "Category", "Tags", "URL", "Images", "Video URL", "Related stories", "Live update", "Source", "Language", "Comments enabled", "Last updated"],
    views: "1.2K+",
    downloads: "108+",
  },
  {
    id: "wikipedia-pages",
    name: "Wikipedia Pages",
    domain: "wikipedia.org",
    desc: "Encyclopedia content: structured info, infobox data, references, and revisions",
    category: "News & Media",
    icon: "W",
    color: "#000000",
    fields: ["Page ID", "Title", "Content", "Summary", "Infobox", "Categories", "References count", "External links", "Images", "Last edited", "Editors count", "Language", "Pageviews", "Related pages", "Coordinates", "URL", "Revision history"],
    views: "2.4K+",
    downloads: "270+",
  },
  {
    id: "substack-newsletters",
    name: "Substack Newsletters",
    domain: "substack.com",
    desc: "Newsletter content: posts, subscriber count, author info, and engagement",
    category: "News & Media",
    icon: "Sb",
    color: "#FF6719",
    fields: ["Publication ID", "Name", "Author", "Description", "Subscribers estimate", "Post title", "Post content", "Date published", "Likes", "Comments", "Is free", "Category", "URL", "Logo", "Frequency", "Top posts", "Social links"],
    views: "1.1K+",
    downloads: "95+",
  },
  {
    id: "snapchat-profiles",
    name: "Snapchat Profiles",
    domain: "snapchat.com",
    desc: "Public profiles: display name, Bitmoji, subscribers, stories, and spotlight",
    category: "Social Media",
    icon: "👻",
    color: "#FFFC00",
    fields: ["Username", "Display name", "Bitmoji", "Subscribers", "Bio", "Profile URL", "Stories count", "Spotlight videos", "Lenses created", "Location", "Website", "Verified", "Public profile", "Last story", "Category"],
    views: "920+",
    downloads: "78+",
  },
];

const ORIGINAL_COUNT = 51;
for (let i = 0; i < ORIGINAL_COUNT; i++) catalog[i].popular = true;

// ─── Merge domain-specific scraper lists into the searchable catalog ──────────
// Amazon scrapers from lib/amazon-scrapers.ts that aren't already in the catalog.
// This ensures search for "amazon" surfaces all Amazon scrapers, not just 2.
const existingIds = new Set(catalog.map((s) => s.id));
const existingNames = new Set(catalog.map((s) => s.name.toLowerCase()));
const amazonFields = ["Title", "Brand", "Price", "Availability", "Reviews count", "Rating", "ASIN", "Categories", "Images", "Seller name", "Description"];

for (const as of AMAZON_SCRAPERS) {
  if (existingIds.has(as.id)) continue;
  // Catalog already has "Amazon Products" (id: amazon-products) — skip duplicate product entry
  if (as.id === "amazon-product" || existingNames.has(as.name.toLowerCase())) continue;
  catalog.push({
    id: as.id,
    name: as.name,
    domain: "amazon.com",
    desc: as.desc,
    category: "E-commerce",
    icon: "A",
    color: "#FF9900",
    fields: amazonFields,
    views: as.views,
    downloads: as.downloads,
    slug: as.id,
  });
  existingIds.add(as.id);
  existingNames.add(as.name.toLowerCase());
}
